# Generated by Django 4.1 on 2022-09-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_posteos_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
