# Generated by Django 4.1 on 2022-09-16 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_alter_posteos_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posteos',
            options={'verbose_name_plural': 'Posteos'},
        ),
        migrations.AlterField(
            model_name='posteos',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
