# Generated by Django 4.1 on 2022-09-16 20:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_posteos_options_alter_posteos_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
