# Generated by Django 4.1 on 2022-09-16 21:03

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_alter_posteos_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('descripcion', models.CharField(max_length=120, verbose_name='Descripcion')),
                ('contenido', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('imagen', models.ImageField(max_length=255, upload_to='')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de  creacion')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Posteos',
            },
        ),
        migrations.DeleteModel(
            name='Posteos',
        ),
    ]
