# Generated by Django 4.1 on 2022-09-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_posteo_contenido_alter_posteo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imgposts'),
        ),
    ]
