# Generated by Django 4.1 on 2022-09-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message_remove_thread_mensaje_delete_mensaje_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='mensaje',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='emisor',
            new_name='user',
        ),
    ]
