# Generated by Django 4.1 on 2022-09-28 20:21

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0004_mensaje_remove_thread_messages_remove_thread_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='_emisor',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='emisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
