# Generated by Django 4.1 on 2022-09-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_remove_mensaje__emisor_mensaje_emisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
